//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"log"
	"os"
	"strings"
	"text/template"
)

var skipLen = map[string]struct{}{
	"NSEC":  {},
	"NSEC3": {},
	"OPT":   {},
	"CSYNC": {},
}

var packageHdr = `
// Code generated by "go run types_generate.go"; DO NOT EDIT.

package dns

import (
	"encoding/base64"
	"net"
)

`

var TypeToRR = template.Must(template.New("TypeToRR").Parse(`
// TypeToRR is a map of constructors for each RR type.
var TypeToRR = map[uint16]func() RR{
{{range .}}{{if ne . "RFC3597"}}  Type{{.}}:  func() RR { return new({{.}}) },
{{end}}{{end}}                    }

`))

var typeToString = template.Must(template.New("typeToString").Parse(`
// TypeToString is a map of strings for each RR type.
var TypeToString = map[uint16]string{
{{range .}}{{if ne . "NSAPPTR"}}  Type{{.}}: "{{.}}",
{{end}}{{end}}                    TypeNSAPPTR:    "NSAP-PTR",
}

`))

var headerFunc = template.Must(template.New("headerFunc").Parse(`
{{range .}}  func (rr *{{.}}) Header() *RR_Header { return &rr.Hdr }
{{end}}

`))

func getTypeStruct(t types.Type, scope *types.Scope) (*types.Struct, bool) {
	_ = "STUB: not implemented"
	return nil, false
}

func loadModule(name string) (*types.Package, error) { _ = "STUB: not implemented"; return nil, nil }

func main() {

	pkg, err := loadModule("github.com/miekg/dns")
	fatalIfErr(err)
	scope := pkg.Scope()

	var numberedTypes []string
	for _, name := range scope.Names() {
		o := scope.Lookup(name)
		if o == nil || !o.Exported() {
			continue
		}
		b, ok := o.Type().(*types.Basic)
		if !ok || b.Kind() != types.Uint16 {
			continue
		}
		if !strings.HasPrefix(o.Name(), "Type") {
			continue
		}
		name := strings.TrimPrefix(o.Name(), "Type")
		if name == "PrivateRR" {
			continue
		}
		numberedTypes = append(numberedTypes, name)
	}

	var namedTypes []string
	for _, name := range scope.Names() {
		o := scope.Lookup(name)
		if o == nil || !o.Exported() {
			continue
		}
		if st, _ := getTypeStruct(o.Type(), scope); st == nil {
			continue
		}
		if name == "PrivateRR" {
			continue
		}

		if scope.Lookup("Type"+o.Name()) == nil && o.Name() != "RFC3597" {
			log.Fatalf("Constant Type%s does not exist.", o.Name())
		}

		namedTypes = append(namedTypes, o.Name())
	}

	b := &bytes.Buffer{}
	b.WriteString(packageHdr)

	fatalIfErr(TypeToRR.Execute(b, namedTypes))

	fatalIfErr(typeToString.Execute(b, numberedTypes))

	fatalIfErr(headerFunc.Execute(b, namedTypes))

	fmt.Fprint(b, "// len() functions\n")
	for _, name := range namedTypes {
		if _, ok := skipLen[name]; ok {
			continue
		}
		o := scope.Lookup(name)
		st, isEmbedded := getTypeStruct(o.Type(), scope)
		if isEmbedded {
			continue
		}
		fmt.Fprintf(b, "func (rr *%s) len(off int, compression map[string]struct{}) int {\n", name)
		fmt.Fprintf(b, "l := rr.Hdr.len(off, compression)\n")
		for i := 1; i < st.NumFields(); i++ {
			o := func(s string) { fmt.Fprintf(b, s, st.Field(i).Name()) }

			if _, ok := st.Field(i).Type().(*types.Slice); ok {
				switch st.Tag(i) {
				case `dns:"-"`:

				case `dns:"cdomain-name"`:
					o("for _, x := range rr.%s { l += domainNameLen(x, off+l, compression, true) }\n")
				case `dns:"domain-name"`:
					o("for _, x := range rr.%s { l += domainNameLen(x, off+l, compression, false) }\n")
				case `dns:"txt"`:
					o("for _, x := range rr.%s { l += len(x) + 1 }\n")
				case `dns:"apl"`:
					o("for _, x := range rr.%s { l += x.len() }\n")
				case `dns:"pairs"`:
					o("for _, x := range rr.%s { l += 4 + int(x.len()) }\n")
				default:
					log.Fatalln(name, st.Field(i).Name(), st.Tag(i))
				}
				continue
			}

			switch {
			case st.Tag(i) == `dns:"-"`:

			case st.Tag(i) == `dns:"cdomain-name"`:
				o("l += domainNameLen(rr.%s, off+l, compression, true)\n")
			case st.Tag(i) == `dns:"domain-name"`:
				o("l += domainNameLen(rr.%s, off+l, compression, false)\n")
			case st.Tag(i) == `dns:"octet"`:
				o("l += len(rr.%s)\n")
			case strings.HasPrefix(st.Tag(i), `dns:"size-base64`):
				fallthrough
			case st.Tag(i) == `dns:"base64"`:
				o("l += base64.StdEncoding.DecodedLen(len(rr.%s))\n")
			case strings.HasPrefix(st.Tag(i), `dns:"size-hex:`):
				o("l += len(rr.%s)/2\n")
			case st.Tag(i) == `dns:"hex"`:
				o("l += len(rr.%s)/2\n")
			case st.Tag(i) == `dns:"any"`:
				o("l += len(rr.%s)\n")
			case st.Tag(i) == `dns:"a"`:
				o("if len(rr.%s) != 0 { l += net.IPv4len }\n")
			case st.Tag(i) == `dns:"aaaa"`:
				o("if len(rr.%s) != 0 { l += net.IPv6len }\n")
			case st.Tag(i) == `dns:"txt"`:
				o("for _, t := range rr.%s { l += len(t) + 1 }\n")
			case st.Tag(i) == `dns:"uint48"`:
				o("l += 6 // %s\n")
			case st.Tag(i) == `dns:"ipsechost"`:
				o(`switch rr.GatewayType {
				case IPSECGatewayIPv4:
					l += net.IPv4len
				case IPSECGatewayIPv6:
					l += net.IPv6len
				case IPSECGatewayHost:
					l += len(rr.%s) + 1
				}
				`)
			case st.Tag(i) == `dns:"amtrelayhost"`:
				o(`switch rr.GatewayType {
				case AMTRELAYIPv4:
					l += net.IPv4len
				case AMTRELAYIPv6:
					l += net.IPv6len
				case AMTRELAYHost:
					l += len(rr.%s) + 1
				}
				`)
			case st.Tag(i) == `dns:"amtrelaytype"`:
				o("l++ // %s\n")
			case st.Tag(i) == "":
				switch st.Field(i).Type().(*types.Basic).Kind() {
				case types.Uint8:
					o("l++ // %s\n")
				case types.Uint16:
					o("l += 2 // %s\n")
				case types.Uint32:
					o("l += 4 // %s\n")
				case types.Uint64:
					o("l += 8 // %s\n")
				case types.String:
					o("l += len(rr.%s) + 1\n")
				default:
					log.Fatalln(name, st.Field(i).Name())
				}
			default:
				log.Fatalln(name, st.Field(i).Name(), st.Tag(i))
			}
		}
		fmt.Fprint(b, "return l }\n\n")
	}

	fmt.Fprint(b, "// copy() functions\n")
	for _, name := range namedTypes {
		o := scope.Lookup(name)
		st, isEmbedded := getTypeStruct(o.Type(), scope)
		fmt.Fprintf(b, "func (rr *%s) copy() RR {\n", name)
		fields := make([]string, 0, st.NumFields())
		if isEmbedded {
			a, _ := o.Type().Underlying().(*types.Struct)
			parent := a.Field(0).Name()
			fields = append(fields, "*rr."+parent+".copy().(*"+parent+")")
			goto WriteCopy
		}
		fields = append(fields, "rr.Hdr")
		for i := 1; i < st.NumFields(); i++ {
			f := st.Field(i).Name()
			if sl, ok := st.Field(i).Type().(*types.Slice); ok {
				t := sl.Underlying().String()
				t = strings.TrimPrefix(t, "[]")
				if idx := strings.LastIndex(t, "."); idx >= 0 {
					t = t[idx+1:]
				}

				if t == "EDNS0" || t == "APLPrefix" || t == "SVCBKeyValue" {
					fmt.Fprintf(b, "%s := make([]%s, len(rr.%s));\nfor i,e := range rr.%s {\n %s[i] = e.copy()\n}\n",
						f, t, f, f, f)
					fields = append(fields, f)
					continue
				}
				fields = append(fields, "cloneSlice(rr."+f+")")
				continue
			}
			if st.Field(i).Type().String() == "net.IP" {
				fields = append(fields, "cloneSlice(rr."+f+")")
				continue
			}
			fields = append(fields, "rr."+f)
		}
	WriteCopy:
		if len(fields) > 3 {
			fmt.Fprintf(b, "return &%s{\n%s,\n}\n", name, strings.Join(fields, ",\n"))
		} else {
			fmt.Fprintf(b, "return &%s{%s}\n", name, strings.Join(fields, ","))
		}
		fmt.Fprint(b, "}\n\n")
	}

	res, err := format.Source(b.Bytes())
	if err != nil {
		b.WriteTo(os.Stderr)
		log.Fatal(err)
	}

	f, err := os.Create("ztypes.go")
	fatalIfErr(err)
	defer f.Close()
	f.Write(res)
}

func fatalIfErr(err error) { _ = "STUB: not implemented"; return }
